export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_ADD_USER = 'FETCH_ADD_USER';
export const FETCH_ADD_USER_REQUEST = 'FETCH_ADD_USER_REQUEST';
export const FETCH_ADD_USER_SUCCESS = 'FETCH_ADD_USER_SUCCESS';
export const FETCH_ADD_USER_ERROR = 'FETCH_ADD_USER_ERROR';

export const FETCH_UPDATE_USER = 'FETCH_UPDATE_USER';
export const FETCH_UPDATE_USER_REQUEST = 'FETCH_UPDATE_USER_REQUEST';
export const FETCH_UPDATE_USER_SUCCESS = 'FETCH_UPDATE_USER_SUCCESS';
export const FETCH_UPDATE_USER_ERROR = 'FETCH_UPDATE_USER_ERROR';

export const FETCH_DELETE_USER = 'FETCH_DELETE_USER';
export const FETCH_DELETE_USER_REQUEST = 'FETCH_DELETE_USER_REQUEST';
export const FETCH_DELETE_USER_SUCCESS = 'FETCH_DELETE_USER_SUCCESS';
export const FETCH_DELETE_USER_ERROR = 'FETCH_DELETE_USER_ERROR';
